env:
  BUILDKITE_ARTIFACT_PATHS: tmp/logs/*.log
  BUILDKITE_GIT_CLEAN_FLAGS: -fq
  LC_ALL: pt_BR.UTF-8
  LANG: pt_BR.UTF-8
  BETA_TESTERS: product,dev
  ALPHA_TESTERS: dev

steps:
- label: 'test'
  command:
  - .buildkite/run setup
  - yarn test
- wait: ~
  branches: "!master"
- label: 'build:ios'
  command:
  - .buildkite/run ios setup,build --profile debug
  branches: "!master"
  concurrency: 1
  concurrency_group: "build:ios"
- label: 'build:android'
  command:
  - .buildkite/run android setup,build --profile debug
  branches: "!master"
  concurrency: 2
  concurrency_group: "build:android"
- wait
- block: "Beta"
  branches: "!master"
- label: 'beta:ios'
  command:
  - .buildkite/run ios setup,assets,bump,build,sign,deploy --profile beta
  env:
    API_URL: https://em-casa-backend-staging.herokuapp.com
  agents:
    queue: deploy
  concurrency: 1
  concurrency_group: "beta:ios"
- label: 'beta:android'
  command:
  - .buildkite/run android setup,assets,bump,build,deploy --profile beta
  env:
    API_URL: https://em-casa-backend-staging.herokuapp.com
  agents:
    queue: deploy
  concurrency: 1
  concurrency_group: "beta:android"
- block: ":rocket: Release"
- label: 'release:ios'
  command:
  - .buildkite/run ios setup,assets,bump,build,sign,deploy --profile production
  env:
    API_URL: https://em-casa-backend.herokuapp.com
  agents:
    queue: deploy
- label: "release:android"
  command:
  - .buildkite/run android setup,assets,bump,build,deploy --profile production
  env:
    API_URL: https://em-casa-backend.herokuapp.com
  agents:
    queue: deploy
