env:
  BUILDKITE_ARTIFACT_PATHS: tmp/logs/*.log
  BUILDKITE_GIT_CLEAN_FLAGS: -fdq
  LC_ALL: pt_BR.UTF-8
  LANG: pt_BR.UTF-8

steps:
- label: 'test'
  command:
  - .buildkite/run setup
  - yarn test
- wait
- label: 'build:ios'
  command:
  - .buildkite/run ios setup
  - .buildkite/run ios build
- label: 'build:android'
  command:
  - .buildkite/run android setup
  - .buildkite/run android build
# - wait
# - label: 'deploy:alpha'
#   branches: !master
#   command: ./deploy.sh $ALPHA_TESTERS
# - label: 'deploy:beta'
#   branches: master
#   command: ./deploy.sh $BETA_TESTERS

