steps:
  - label: 'test'
    command:
    - .buildkite/setup.sh
    - yarn test
  - wait
  - label: 'build:ios'
    command: .buildkite/build.sh ios
  - label: 'build:android'
    command: .buildkite/build.sh android
  # - wait
  # - label: 'deploy:alpha'
  #   branches: !master
  #   command: ./deploy.sh $ALPHA_TESTERS
  # - label: 'deploy:beta'
  #   branches: master
  #   command: ./deploy.sh $BETA_TESTERS

