steps:
  - label: 'test'
    command:
    - .buildkite/setup.sh
    - yarn test
  - wait
  - label: 'build:ios'
    command:
    - .buildkite/setup.sh ios
    - .buildkite/build-ios.sh
  - label: 'build:android'
    command:
    - .buildkite/setup.sh android
    - .buildkite/build.sh
  # - wait
  # - label: 'deploy:alpha'
  #   branches: !master
  #   command: ./deploy.sh $ALPHA_TESTERS
  # - label: 'deploy:beta'
  #   branches: master
  #   command: ./deploy.sh $BETA_TESTERS

