env:
  BUILDKITE_ARTIFACT_PATHS: tmp/logs/*.log
  BUILDKITE_GIT_CLEAN_FLAGS: -fdq
  LC_ALL: pt_BR.UTF-8
  LANG: pt_BR.UTF-8
  BETA_TESTERS: product,dev
  ALPHA_TESTERS: dev

steps:
- label: 'test'
  command:
  - .buildkite/run setup
  - yarn test
- wait
- label: 'build:ios'
  command:
  - .buildkite/run ios setup,assets,bump,build --bump
  - (cd ios/build && zip -r EmCasa.xcarchive.zip EmCasa.xcarchive)
  - buildkite-agent artifact upload "ios/build/EmCasa.xcarchive.zip"
  - buildkite-agent artifact upload "ios/build/EmCasa.xcarchive/Info.plist"
- label: 'build:android'
  command:
  - .buildkite/run android setup,assets,bump,build --bump
  - buildkite-agent artifact upload "android/app/build/outputs/apk/app-release.apk"
- wait
- label: 'beta:ios'
  command:
  - buildkite-agent artifact download "ios/build/EmCasa.xcarchive.zip" . --step "build:ios"
  - (cd ios/build && unzip EmCasa.xcarchive.zip)
  - buildkite-agent artifact download "ios/build/EmCasa.xcarchive/Info.plist" . --step "build:ios"
  - .buildkite/run ios setup,sign,deploy -p beta
- label: 'beta:android'
  command:
  - buildkite-agent artifact download "android/app/build/outputs/apk/app-release.apk" . --step "build:android"
  - .buildkite/run setup
  - .buildkite/run android deploy -p beta
